############################
## General Configurations ##
############################

homeassistant: !include homeassistant.yaml

http: !include http.yaml

frontend:
updater:
sun:
history:
logbook:
conversation:

group: !include group.yaml


# mqtt:
#   broker: 127.0.0.1
#   port: 1883
#   client_id: home-assistant-1
#   username: pi
#   password: raspberry

##############
## Software ##
##############
device_tracker: !include device_tracker.yaml

emulated_hue:
  host_ip: !secret pi_ip

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

##############
## Hardware ##
##############

light:
  - platform: hue
    host: 192.168.0.201
    allow_unreachable: true
  - platform: lifx
    broadcast: 192.168.0.255

zwave:
  usb_path: /dev/ttyACM0
