############################
## General Configurations ##
############################

homeassistant: !include homeassistant.yaml

http: !include http.yaml

frontend:
updater:
history:
logbook:
conversation:

group: !include group.yaml

automation: !include_dir_list automation
scene: !include_dir_list scenes
input_boolean: !include input_boolean.yaml

# mqtt:
#   broker: 127.0.0.1
#   port: 1883
#   client_id: home-assistant-1
#   username: pi
#   password: raspberry

##############
## Software ##
##############
device_tracker: !include device_tracker.yaml

notify: !include notify.yaml

# Weather Prediction
sensor:
  platform: yr

sun:

##############
## Hardware ##
##############

light:
  - platform: hue
    host: 192.168.0.201
    allow_unreachable: true
    allow_hue_groups: false
  - platform: lifx
    broadcast: 192.168.0.255

emulated_hue:
  host_ip: !secret pi_ip
  expose_by_default: false

zwave:
  usb_path: /dev/ttyACM0
