############################
## General Configurations ##
############################

homeassistant: !include homeassistant.yaml

http: !include http.yaml

frontend:
updater:
sun:
history:
logbook:
conversation:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google


mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

##############
## Hardware ##
##############

light:
  - platform: hue
    host: 192.168.0.201
    allow_unreachable: true
  - platform: lifx

zwave:
  usb_path: /dev/ttyACM0
