alias: "Pushbullet Notifications when someone is almost home"
hide_entity: true
trigger:
  platform: state
  entity_id:
    - device_tracker.2fca3e09d69842a88d1147d6d010e99e
  to: 'almost home'
action:
  service: notify.wills_notify
  data:
    title: "Dad's Almost Home"
    message: "Dad is almost home"
    target: "device/Anubis"
