alias: "Pushbullet Notifications when someone comes home"
hide_entity: true
trigger:
  platform: state
  entity_id: group.parents
  to: 'almost home'
action:
  service: notify.wills_notify
  data:
    title: "Almost Home"
    message: "Parent is almost home"
