alias: "Pushbullet Notifications when someone is almost home"
trigger:
  platform: state
  entity_id:
    - device_tracker.1a6ab810cf3d45608ad16b2f761b5043
    - device_tracker.2fca3e09d69842a88d1147d6d010e99e
    - device_tracker.7ec950f9d4f84cac94c0eddb9de85823
  to: 'almost home'
action:
  service: notify.wills_notify
  data:
    title: "Almost Home"
    message: "Parent is almost home"
