alias: "Pushbullet Notifications when someone comes home"
hide_entity: true
trigger:
  platform: state
  entity_id:
    - device_tracker.2fca3e09d69842a88d1147d6d010e99e
  to: 'home'
action:
  service: notify.wills_notify
  data:
    title: "Dad's Home"
    message: "Dad is home"
    target: "device/Anubis"
