alias: "Pushbullet Notifications when someone comes home"
hide_entity: true
trigger:
  platform: state
  entity_id:
    - device_tracker.7ec950f9d4f84cac94c0eddb9de85823
  to: 'home'
action:
  service: notify.wills_notify
  data:
    title: "Mom's Home"
    message: "Mom is home"
