alias: "Pushbullet Notifications when someone comes home"
trigger:
  platform: state
  entity_id: group.parents
  to: 'home'
action:
  service: notify.wills_notify
  data:
    title: "Home"
    message: "Parent is home"
