alias: 'Turn off all lights if no ones home'
trigger:
  platform: state
  entity_id: group.all_mobile_devices
  to: 'not_home'
condition:
- condition: state
  entity_id: device_tracker.1a6ab810cf3d45608ad16b2f761b5043 #Will
  state: 'not_home'
- condition: state
  entity_id: device_tracker.7ec950f9d4f84cac94c0eddb9de85823 #Robin
  state: 'not_home'
- condition: state
  entity_id: device_tracker.2fca3e09d69842a88d1147d6d010e99e # Rod
  state: 'not_home'
- condition: state
  entity_id: input_boolean.simulate_presence
  state: 'off'
action:
  service: light.turn_off
  entity_id: group.all_lights
