alias: 'Turn on all lights when someone comes home after sunset(ish)'
trigger:
  platform: state
  entity_id: group.all_mobile_devices
  to: 'home'
condition: 
  condition: sun
  after: sunset
  after_offset: "-1:00:00"
action:
  service: light.turn_on
  entity_id: group.all_lights